name: Build and Release new

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      - name: Build EXE
        shell: msys2 {0}
        run: |
          gcc main.c -o calculator.exe

      - name: Delete old release
        continue-on-error: true
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          files: calculator.exe
