name: Build and Publish

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: cmd
        run: |
          cl /EHsc main.c /Fe:calculator.exe

      - name: Delete old latest release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        continue-on-error: true
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          files: calculator.exe
